import type { NextApiRequest, NextApiResponse } from 'next'

const TOUTES_CATEGORIES = [
  'Littérature', 'Philosophie', 'Sciences', 'Histoire',
  'Vie quotidienne', 'Art', 'Gastronomie', 'Nature', 'Politique', 'Sport'
]

const BANQUE: any[] = [
  // LITTÉRATURE
  { mot: "Palimpseste", nature: "nom masculin", theme: "Littérature", type: "mot", definition: "Parchemin dont on a effacé l'écriture pour y écrire un nouveau texte, mais dont les traces originales restent visibles.", etymologie: "Du grec palímpsestos — « gratté de nouveau »", exemples: [{ texte: "Cette ville est un palimpseste vivant : sous chaque façade moderne affleurent des traces médiévales.", contexte: "Usage figuré" }, { texte: "Sa mémoire était un palimpseste : les souvenirs d'enfance transparaissaient sous les années.", contexte: "Métaphore poétique" }, { texte: "L'archéologue étudia avec soin le palimpseste découvert dans le monastère.", contexte: "Contexte historique" }], quiz: { correct: "Parchemin dont l'écriture originale reste visible sous un nouveau texte.", wrongs: ["Ornement architectural antique.", "Technique picturale à la cire.", "Instrument à cordes pincées."], anecdote: "Un palimpseste révèle les traces du passé sous le présent — une belle métaphore pour la mémoire !" } },
  { mot: "Catharsis", nature: "nom féminin", theme: "Littérature", type: "mot", definition: "Purification des passions par l'art, notamment le théâtre ; soulagement émotionnel profond.", etymologie: "Du grec katharsis — « purification »", exemples: [{ texte: "La tragédie grecque visait la catharsis : faire pleurer le spectateur pour le libérer.", contexte: "Histoire du théâtre" }, { texte: "Écrire ce roman fut pour lui une véritable catharsis.", contexte: "Création littéraire" }, { texte: "La psychanalyse utilise la catharsis pour libérer les traumatismes.", contexte: "Psychologie" }], quiz: { correct: "Purification des passions par l'art ; soulagement émotionnel.", wrongs: ["Technique rhétorique.", "Procédé de distillation.", "Forme de méditation."], anecdote: "Aristote pensait que pleurer au théâtre était sain — cela purgeait les émotions négatives !" } },
  { mot: "Apocryphe", nature: "adjectif", theme: "Littérature", type: "mot", definition: "Dont l'authenticité est douteuse ou contestée ; non reconnu comme authentique.", etymologie: "Du grec apokryphos — « caché, secret »", exemples: [{ texte: "Ce tableau attribué à Rembrandt est considéré comme apocryphe.", contexte: "Art" }, { texte: "De nombreuses citations apocryphes circulent sur Internet.", contexte: "Culture numérique" }, { texte: "Les évangiles apocryphes racontent la vie de Jésus de manière non officielle.", contexte: "Religion" }], quiz: { correct: "Dont l'authenticité est douteuse ou non reconnue.", wrongs: ["Écrit en caractères anciens.", "Provenant d'une source étrangère.", "Réservé aux initiés."], anecdote: "La plupart des citations célèbres sur internet sont apocryphes !" } },
  { mot: "Laconique", nature: "adjectif", theme: "Littérature", type: "mot", definition: "Qui s'exprime en peu de mots ; bref et concis.", etymologie: "Du grec Lakônikos — relatif à la Laconie, région dont les habitants parlaient peu", exemples: [{ texte: "Sa réponse laconique — « Non. » — ne laissait aucune place au débat.", contexte: "Communication directe" }, { texte: "Le style laconique d'Hemingway était révolutionnaire.", contexte: "Critique littéraire" }, { texte: "Ses emails laconiques étaient efficaces mais perçus comme froids.", contexte: "Professionnel" }], quiz: { correct: "Qui s'exprime en peu de mots, bref et concis.", wrongs: ["Qui parle sans s'arrêter.", "Qui utilise beaucoup de métaphores.", "Qui s'exprime uniquement par écrit."], anecdote: "Quand Philippe de Macédoine menaça Sparte, les Spartiates répondirent en un seul mot : « Si » !" } },
  { mot: "Aphorisme", nature: "nom masculin", theme: "Littérature", type: "mot", definition: "Courte formule exprimant une vérité générale de manière concise et frappante.", etymologie: "Du grec aphorismos — « définition »", exemples: [{ texte: "« Connais-toi toi-même » est l'aphorisme le plus célèbre de l'Antiquité.", contexte: "Philosophie antique" }, { texte: "Oscar Wilde était maître de l'aphorisme.", contexte: "Littérature" }, { texte: "Son carnet était rempli d'aphorismes personnels.", contexte: "Usage personnel" }], quiz: { correct: "Courte formule exprimant une vérité générale de manière concise.", wrongs: ["Long poème philosophique.", "Résumé scientifique.", "Définition technique."], anecdote: "Pascal : « Je n'ai fait celle-ci plus longue que parce que je n'ai pas eu le loisir de la faire plus courte » !" } },
  // PHILOSOPHIE
  { mot: "Catharsis", nature: "nom féminin", theme: "Philosophie", type: "mot", definition: "Libération des tensions intérieures par la prise de conscience ou l'expression.", etymologie: "Du grec katharsis — « purification »", exemples: [{ texte: "Sa thérapie fut une véritable catharsis.", contexte: "Psychologie" }, { texte: "L'art permet une catharsis collective.", contexte: "Sociologie" }, { texte: "Il trouva la catharsis dans l'écriture de son journal.", contexte: "Usage personnel" }], quiz: { correct: "Libération des tensions par la prise de conscience.", wrongs: ["Accumulation de frustrations.", "Technique de manipulation.", "Forme de déni."], anecdote: "Freud s'est inspiré d'Aristote pour développer la catharsis en psychanalyse !" } },
  { mot: "Stoïcisme", nature: "nom masculin", theme: "Philosophie", type: "mot", definition: "Attitude de fermeté et d'impassibilité face aux épreuves ; doctrine philosophique antique.", etymologie: "Du grec stoikos — « du portique », lieu où enseignait Zénon", exemples: [{ texte: "Il accueillit la mauvaise nouvelle avec un stoïcisme admirable.", contexte: "Réaction personnelle" }, { texte: "Le stoïcisme enseigne que seul ce qui dépend de nous mérite attention.", contexte: "Philosophie pratique" }, { texte: "Marc Aurèle fut l'exemple du dirigeant stoïcien.", contexte: "Histoire" }], quiz: { correct: "Fermeté face aux épreuves et doctrine philosophique antique.", wrongs: ["Recherche du plaisir immédiat.", "Pessimisme systématique.", "Indifférence à la souffrance d'autrui."], anecdote: "Épictète était esclave — sa liberté intérieure totale est le symbole du stoïcisme !" } },
  { mot: "Ubiquité", nature: "nom féminin", theme: "Philosophie", type: "mot", definition: "Capacité supposée d'être présent en plusieurs endroits à la fois.", etymologie: "Du latin ubique — « partout »", exemples: [{ texte: "Il avait le don d'ubiquité : on le croisait partout.", contexte: "Usage hyperbolique" }, { texte: "Internet a créé une ubiquité numérique de l'information.", contexte: "Monde digital" }, { texte: "Le manager se plaignait de ne pas avoir le don d'ubiquité.", contexte: "Vie professionnelle" }], quiz: { correct: "Capacité supposée d'être présent en plusieurs endroits.", wrongs: ["Art de se rendre invisible.", "Faculté de mémoriser des lieux.", "Capacité à communiquer par la pensée."], anecdote: "Seul Dieu peut être partout à la fois — voilà pourquoi l'ubiquité fascine les philosophes !" } },
  { mot: "Nihilisme", nature: "nom masculin", theme: "Philosophie", type: "mot", definition: "Doctrine qui nie toute valeur morale ou métaphysique ; refus de tout principe établi.", etymologie: "Du latin nihil — « rien »", exemples: [{ texte: "Le nihilisme de Nietzsche était une réponse à la mort de Dieu.", contexte: "Philosophie" }, { texte: "Son nihilisme apparent cachait une blessure profonde.", contexte: "Psychologie" }, { texte: "Le mouvement punk était imprégné d'un nihilisme provocateur.", contexte: "Culture" }], quiz: { correct: "Doctrine qui nie toute valeur morale ou principe établi.", wrongs: ["Philosophie célébrant la beauté.", "Croyance en une vie après la mort.", "Doctrine affirmant que tout a un sens."], anecdote: "Nietzsche ne prônait pas le nihilisme — il le diagnostiquait comme maladie à dépasser !" } },
  { mot: "Velléitaire", nature: "adjectif", theme: "Philosophie", type: "mot", definition: "Qui n'a que des intentions faibles, sans jamais passer à l'acte ; qui manque de volonté.", etymologie: "Du latin velleitas — « volonté faible »", exemples: [{ texte: "Son attitude velléitaire l'empêchait de mener ses projets à terme.", contexte: "Caractère" }, { texte: "Il était trop velléitaire pour s'imposer une discipline.", contexte: "Usage courant" }, { texte: "La politique velléitaire du gouvernement déçut ses partisans.", contexte: "Politique" }], quiz: { correct: "Qui n'a que des intentions faibles et ne passe jamais à l'acte.", wrongs: ["Qui agit avec énergie exceptionnelle.", "Qui change d'avis par prudence.", "Qui souffre de timidité."], anecdote: "Un velléitaire veut tout mais ne fait rien — la velléité est l'antichambre de l'inaction !" } },
  // SCIENCES
  { mot: "Sérendipité", nature: "nom féminin", theme: "Sciences", type: "mot", definition: "Faculté de faire par hasard des découvertes heureuses tout en cherchant autre chose.", etymologie: "De l'anglais serendipity, forgé par Horace Walpole d'après un conte persan", exemples: [{ texte: "La découverte de la pénicilline est un exemple de sérendipité.", contexte: "Histoire des sciences" }, { texte: "C'est par sérendipité qu'il trouva l'amour de sa vie.", contexte: "Romantique" }, { texte: "La sérendipité est sous-estimée dans les grandes découvertes.", contexte: "Réflexion" }], quiz: { correct: "Découvertes heureuses faites par hasard en cherchant autre chose.", wrongs: ["Art de prévoir les événements.", "Capacité à mémoriser.", "Technique de méditation."], anecdote: "Fleming cherchait un antibiotique et une moisissure contamina sa boîte — c'était la pénicilline !" } },
  { mot: "Paradigme", nature: "nom masculin", theme: "Sciences", type: "mot", definition: "Modèle théorique dominant qui oriente la recherche scientifique d'une époque.", etymologie: "Du grec paradeigma — « modèle, exemple »", exemples: [{ texte: "La révolution copernicienne fut un changement de paradigme majeur.", contexte: "Histoire des sciences" }, { texte: "Le numérique a imposé un nouveau paradigme dans la musique.", contexte: "Économie" }, { texte: "Nous vivons un changement de paradigme dans notre rapport au travail.", contexte: "Société" }], quiz: { correct: "Modèle théorique dominant qui oriente la pensée d'une époque.", wrongs: ["Règles grammaticales.", "Appareil de mesure.", "Technique de présentation."], anecdote: "Thomas Kuhn a montré que la science avance par révolutions, par sauts de paradigme !" } },
  { mot: "Heuristique", nature: "adjectif", theme: "Sciences", type: "mot", definition: "Qui sert à la découverte, qui favorise la recherche en stimulant la réflexion.", etymologie: "Du grec heuriskein — « trouver »", exemples: [{ texte: "La méthode heuristique encourage l'élève à découvrir par lui-même.", contexte: "Pédagogie" }, { texte: "L'IA utilise des algorithmes heuristiques.", contexte: "Informatique" }, { texte: "Cette question heuristique ouvrit des pistes inattendues.", contexte: "Méthode scientifique" }], quiz: { correct: "Qui sert à la découverte et favorise la recherche.", wrongs: ["Qui empêche la réflexion.", "Qui impose une solution unique.", "Qui mesure les performances."], anecdote: "Eurêka ! — le cri d'Archimède vient du même grec que heuristique : trouver !" } },
  { mot: "Atavisme", nature: "nom masculin", theme: "Sciences", type: "mot", definition: "Réapparition de caractères ancestraux après plusieurs générations ; tendance héréditaire.", etymologie: "Du latin atavus — « ancêtre »", exemples: [{ texte: "Son amour pour la mer était un atavisme — ses ancêtres étaient marins.", contexte: "Héritage familial" }, { texte: "Les scientifiques étudient l'atavisme pour comprendre l'évolution.", contexte: "Biologie" }, { texte: "Cet atavisme culturel explique pourquoi certaines traditions perdurent.", contexte: "Sociologie" }], quiz: { correct: "Réapparition de caractères ancestraux après plusieurs générations.", wrongs: ["Mutation génétique provoquée.", "Tendance à imiter ses contemporains.", "Régression vers l'état infantile."], anecdote: "Certains humains naissent avec une queue vestigiale — de l'atavisme, un rappel de nos ancêtres !" } },
  // HISTOIRE
  { mot: "Ostracisme", nature: "nom masculin", theme: "Histoire", type: "mot", definition: "Exclusion d'une personne d'un groupe par une décision collective.", etymologie: "Du grec ostrakon — « coquille », les Athéniens votaient sur des tessons de poterie", exemples: [{ texte: "Il fut victime d'ostracisme après avoir dénoncé les pratiques de l'entreprise.", contexte: "Professionnel" }, { texte: "L'ostracisme social a des effets dévastateurs sur la santé mentale.", contexte: "Psychologie" }, { texte: "À Athènes, l'ostracisme permettait d'exiler un citoyen dangereux.", contexte: "Histoire" }], quiz: { correct: "Exclusion d'une personne d'un groupe par décision collective.", wrongs: ["Cérémonie de bienvenue.", "Technique diplomatique.", "Taxation sur le luxe."], anecdote: "À Athènes, 6000 votes suffisaient pour exiler quelqu'un 10 ans — gravés sur des tessons !" } },
  { mot: "Hégémonie", nature: "nom féminin", theme: "Histoire", type: "mot", definition: "Domination politique, culturelle ou économique d'un État ou groupe sur les autres.", etymologie: "Du grec hêgemonia — « commandement »", exemples: [{ texte: "L'hégémonie américaine est contestée depuis les années 2000.", contexte: "Géopolitique" }, { texte: "La Silicon Valley exerce une hégémonie culturelle mondiale.", contexte: "Économie" }, { texte: "Athènes cherchait à établir son hégémonie sur la Grèce.", contexte: "Antiquité" }], quiz: { correct: "Domination d'un État ou groupe sur les autres.", wrongs: ["Alliance défensive.", "Système d'échange équitable.", "Philosophie de l'égalité."], anecdote: "Sparte et Athènes se sont battues 27 ans pour l'hégémonie — la guerre du Péloponnèse !" } },
  { mot: "Prosélytisme", nature: "nom masculin", theme: "Histoire", type: "mot", definition: "Zèle ardent pour recruter des adeptes à une cause, une religion ou une idéologie.", etymologie: "Du grec prosêlytos — « nouveau venu »", exemples: [{ texte: "Son prosélytisme végane agaçait ses amis.", contexte: "Mode de vie" }, { texte: "Le prosélytisme religieux est encadré par la loi.", contexte: "Droit" }, { texte: "Elle faisait du prosélytisme pour sa nouvelle application.", contexte: "Technologie" }], quiz: { correct: "Zèle ardent pour recruter des adeptes.", wrongs: ["Art de la dispute médiévale.", "Technique de vente douce.", "Mouvement artistique populaire."], anecdote: "Les premiers chrétiens étaient des prosélytes — le mot désignait les convertis au judaïsme !" } },
  // VIE QUOTIDIENNE
  { mot: "Velléitaire", nature: "adjectif", theme: "Vie quotidienne", type: "mot", definition: "Qui reste au stade des bonnes intentions sans jamais passer à l'action.", etymologie: "Du latin velleitas — « volonté faible »", exemples: [{ texte: "Il parlait de faire du sport depuis des années sans jamais commencer — un velléitaire.", contexte: "Usage courant" }, { texte: "Son rapport au régime était velléitaire : résolutions le lundi, abandon le mardi.", contexte: "Humour" }, { texte: "Ne sois pas velléitaire, inscris-toi maintenant !", contexte: "Conseil pratique" }], quiz: { correct: "Qui reste aux bonnes intentions sans passer à l'acte.", wrongs: ["Qui agit impulsivement.", "Qui planifie avec soin.", "Qui délègue toutes ses tâches."], anecdote: "On dit que l'enfer est pavé de bonnes intentions — c'est le territoire du velléitaire !" } },
  { mot: "Tergiverser", nature: "verbe", theme: "Vie quotidienne", type: "mot", definition: "User de détours pour éviter de prendre une décision claire.", etymologie: "Du latin tergiversari — « tourner le dos »", exemples: [{ texte: "Arrête de tergiverser et donne-moi une réponse !", contexte: "Injonction" }, { texte: "Le ministre tergiversa des semaines avant d'annoncer sa décision.", contexte: "Politique" }, { texte: "Sa tendance à tergiverser lui coûtait des opportunités.", contexte: "Caractère" }], quiz: { correct: "User de détours pour éviter de décider.", wrongs: ["Parler avec éloquence.", "Changer d'opinion brutalement.", "Agir avec précipitation."], anecdote: "Tourner le dos en latin — tergiverser c'est littéralement fuir la réalité !" } },
  { mot: "Circonspect", nature: "adjectif", theme: "Vie quotidienne", type: "mot", definition: "Qui agit avec prudence en pesant soigneusement les conséquences.", etymologie: "Du latin circumspectus — « qui regarde autour de soi »", exemples: [{ texte: "Face à cette proposition, il fut circonspect et demanda des garanties.", contexte: "Affaires" }, { texte: "Sa réponse circonspecte trahissait une méfiance.", contexte: "Relation" }, { texte: "Sois circonspect avant de signer ce contrat.", contexte: "Conseil" }], quiz: { correct: "Qui agit avec prudence en pesant les conséquences.", wrongs: ["Qui parle sans réfléchir.", "Qui agit impulsivement.", "Qui fait confiance facilement."], anecdote: "Regarder autour de soi avant d'agir — les Romains avaient compris que la prudence est sagesse !" } },
  // ART
  { mot: "Iconoclaste", nature: "adjectif", theme: "Art", type: "mot", definition: "Qui s'attaque aux idées reçues et aux traditions établies ; briseur de conventions.", etymologie: "Du grec eikôn (image) et klaein (briser)", exemples: [{ texte: "Son approche iconoclaste bouleversa les certitudes de l'époque.", contexte: "Sciences" }, { texte: "Cet artiste iconoclaste refusait toutes les conventions.", contexte: "Art contemporain" }, { texte: "La réforme protestante fut un mouvement iconoclaste.", contexte: "Histoire" }], quiz: { correct: "Qui s'attaque aux idées reçues et traditions établies.", wrongs: ["Qui collectionne les icônes.", "Qui défend les traditions.", "Qui crée des icônes numériques."], anecdote: "Au VIIIe siècle, les iconoclastes brisaient littéralement les icônes — l'Église s'en est remise !" } },
  { mot: "Synesthésie", nature: "nom féminin", theme: "Art", type: "mot", definition: "Phénomène par lequel un sens en évoque un autre spontanément, comme voir des couleurs en entendant de la musique.", etymologie: "Du grec syn (ensemble) et aisthesis (sensation)", exemples: [{ texte: "Sa synesthésie lui faisait voir les notes de musique en couleurs.", contexte: "Neurologie" }, { texte: "Kandinsky peignait en synesthésie — chaque couleur correspondait à un son.", contexte: "Art" }, { texte: "La synesthésie est un don rare qui enrichit la perception artistique.", contexte: "Créativité" }], quiz: { correct: "Un sens en évoque un autre spontanément.", wrongs: ["Perte totale d'un sens.", "Technique picturale abstraite.", "Mélange de deux styles artistiques."], anecdote: "Rimbaud voyait des couleurs dans les voyelles — A noir, E blanc, I rouge, U vert, O bleu !" } },
  { mot: "Chiaroscuro", nature: "nom masculin", theme: "Art", type: "mot", definition: "Technique picturale jouant sur les contrastes de lumière et d'ombre pour donner du relief.", etymologie: "De l'italien chiaro (clair) et scuro (sombre)", exemples: [{ texte: "Le chiaroscuro du Caravage révolutionna la peinture baroque.", contexte: "Histoire de l'art" }, { texte: "La photographe maîtrisait le chiaroscuro pour donner du drame à ses portraits.", contexte: "Photographie" }, { texte: "Ce film noir utilise le chiaroscuro comme signature visuelle.", contexte: "Cinéma" }], quiz: { correct: "Technique jouant sur les contrastes de lumière et d'ombre.", wrongs: ["Mélange de plusieurs styles picturaux.", "Art de la fresque sur plâtre humide.", "Technique de sculpture en bas-relief."], anecdote: "Le Caravage était si expert du chiaroscuro qu'on disait que ses tableaux avaient l'air de sortir du mur !" } },
  { mot: "Kitsch", nature: "adjectif / nom masculin", theme: "Art", type: "mot", definition: "Qui est de mauvais goût de façon outrancière mais souvent assumée et plaisante.", etymologie: "De l'allemand kitschen — « bâcler »", exemples: [{ texte: "Sa décoration kitsch assumée amusait ses invités.", contexte: "Intérieur" }, { texte: "Le kitsch des années 80 revient en force dans la mode actuelle.", contexte: "Mode" }, { texte: "Andy Warhol a élevé le kitsch au rang d'art contemporain.", contexte: "Art" }], quiz: { correct: "De mauvais goût outrancier mais souvent assumé.", wrongs: ["D'une élégance sobre et raffinée.", "D'une précision technique irréprochable.", "D'une austérité minimaliste."], anecdote: "Warhol disait : « Le kitsch est la culture de masse » — il en a fait un manifeste artistique !" } },
  // GASTRONOMIE
  { mot: "Umami", nature: "nom masculin", theme: "Gastronomie", type: "mot", definition: "Cinquième saveur fondamentale, après le sucré, salé, acide et amer ; saveur savoureuse et profonde.", etymologie: "Du japonais umai (délicieux) et mi (goût)", exemples: [{ texte: "Le parmesan et les anchois sont riches en umami.", contexte: "Cuisine" }, { texte: "Les chefs utilisent l'umami pour donner de la profondeur à leurs plats.", contexte: "Gastronomie" }, { texte: "La sauce soja est l'une des sources d'umami les plus connues.", contexte: "Cuisine asiatique" }], quiz: { correct: "Cinquième saveur fondamentale, savoureuse et profonde.", wrongs: ["Épice japonaise très piquante.", "Technique de cuisson à la vapeur.", "Type de sauce fermentée."], anecdote: "L'umami a été découvert en 1908 par un chimiste japonais qui étudiait le bouillon d'algues !" } },
  { mot: "Millésime", nature: "nom masculin", theme: "Gastronomie", type: "mot", definition: "Année de récolte d'un vin ou d'une production ; par extension, toute référence à une excellente année.", etymologie: "Du latin millesimus — « millième »", exemples: [{ texte: "Ce bordeaux d'un millésime exceptionnel se vendait une fortune.", contexte: "Oenologie" }, { texte: "Le millésime 1982 est considéré comme légendaire à Bordeaux.", contexte: "Histoire viticole" }, { texte: "Ce film est un vrai millésime — il ne vieillit pas.", contexte: "Usage figuré" }], quiz: { correct: "Année de récolte d'un vin ; excellente production.", wrongs: ["Cépage particulièrement rare.", "Méthode de vinification traditionnelle.", "Température idéale de dégustation."], anecdote: "Les vignerons parlent de « grands millésimes » comme les astronomes d'étoiles — chaque année est unique !" } },
  { mot: "Fricassée", nature: "nom féminin", theme: "Gastronomie", type: "mot", definition: "Préparation culinaire de viande ou légumes revenus puis mijotés dans une sauce.", etymologie: "De fricare (frotter) et casser — « frire et casser en morceaux »", exemples: [{ texte: "La fricassée de poulet à la crème est un classique de la cuisine bourgeoise.", contexte: "Cuisine française" }, { texte: "Il prépara une fricassée de champignons sauvages ramassés le matin.", contexte: "Cuisine saisonnière" }, { texte: "Par extension, une fricassée désigne un mélange confus d'éléments hétéroclites.", contexte: "Usage figuré" }], quiz: { correct: "Préparation de viande revenue puis mijotée en sauce.", wrongs: ["Technique de conservation par le sel.", "Dessert à base de fruits frits.", "Méthode de cuisson au four."], anecdote: "La fricassée apparaît dans les textes français dès le XIVe siècle — c'est l'un des plus vieux mots de la cuisine française !" } },
  { mot: "Mijoter", nature: "verbe", theme: "Gastronomie", type: "mot", definition: "Cuire lentement à feu doux ; au figuré, préparer quelque chose en secret.", etymologie: "Origine obscure, peut-être du latin mijotare", exemples: [{ texte: "Le bœuf bourguignon mijote depuis ce matin — il sera parfait ce soir.", contexte: "Cuisine" }, { texte: "Elle mijotait quelque chose depuis des semaines.", contexte: "Usage figuré" }, { texte: "Les meilleurs plats mijotent longtemps, comme les meilleures idées.", contexte: "Sagesse culinaire" }], quiz: { correct: "Cuire lentement à feu doux ou préparer en secret.", wrongs: ["Cuire à très haute température.", "Servir un plat immédiatement.", "Congeler pour une conservation longue."], anecdote: "La cuisine lente (slow cooking) est une redécouverte moderne d'une sagesse millénaire — nos grands-mères le savaient !" } },
  // NATURE
  { mot: "Sylvestre", nature: "adjectif", theme: "Nature", type: "mot", definition: "Qui appartient à la forêt, qui vit ou croît dans les bois.", etymologie: "Du latin silvester — « de la forêt »", exemples: [{ texte: "L'atmosphère sylvestre de cette clairière invitait à la rêverie.", contexte: "Description poétique" }, { texte: "Le pin sylvestre est l'une des essences les plus répandues en France.", contexte: "Botanique" }, { texte: "Ces créatures sylvestres vivaient loin de toute habitation humaine.", contexte: "Nature" }], quiz: { correct: "Qui appartient à la forêt, qui vit dans les bois.", wrongs: ["Qui vit dans les déserts.", "Qui habite les zones côtières.", "Qui prospère en haute montagne."], anecdote: "Silvestre — Sylvain — Sylvie : tous ces prénoms viennent de silva, la forêt en latin !" } },
  { mot: "Estivage", nature: "nom masculin", theme: "Nature", type: "mot", definition: "Migration saisonnière des troupeaux vers les pâturages d'altitude en été.", etymologie: "Du latin aestivus — « d'été »", exemples: [{ texte: "L'estivage dans les Alpes est une tradition pastorale millénaire.", contexte: "Agriculture" }, { texte: "Les sonnailles des vaches signalaient l'estivage dans toute la vallée.", contexte: "Tradition" }, { texte: "Le retour de l'estivage en automne est une fête dans de nombreux villages.", contexte: "Culture" }], quiz: { correct: "Migration saisonnière des troupeaux vers les pâturages d'altitude.", wrongs: ["Technique d'irrigation des champs.", "Festival de la moisson en été.", "Migration des oiseaux vers le sud."], anecdote: "La désalpe en Suisse et en Savoie est une fête — les vaches descendent des alpages ornées de fleurs !" } },
  { mot: "Frondaison", nature: "nom féminin", theme: "Nature", type: "mot", definition: "Ensemble du feuillage d'un arbre ou d'une forêt ; époque de la pousse des feuilles.", etymologie: "Du latin frons, frondis — « feuillage »", exemples: [{ texte: "La frondaison printanière transformait la forêt en cathédrale verte.", contexte: "Description poétique" }, { texte: "Le bruissement des frondaisons dans le vent était apaisant.", contexte: "Nature" }, { texte: "L'oiseau construisit son nid dans l'épaisse frondaison du chêne.", contexte: "Observation naturelle" }], quiz: { correct: "Ensemble du feuillage d'un arbre ou d'une forêt.", wrongs: ["Chute des feuilles en automne.", "Système racinaire d'un grand arbre.", "Écorce protectrice des arbres anciens."], anecdote: "Les druides celtes vénéraient les frondaisons du chêne — le gui qui y poussait était sacré !" } },
  // POLITIQUE
  { mot: "Démagogie", nature: "nom féminin", theme: "Politique", type: "mot", definition: "Art de flatter les passions populaires pour acquérir ou conserver le pouvoir.", etymologie: "Du grec dêmos (peuple) et agein (conduire)", exemples: [{ texte: "Sa démagogie facile trouvait un écho dans les masses désemparées.", contexte: "Politique" }, { texte: "La démagogie est le contraire du courage politique.", contexte: "Réflexion civique" }, { texte: "Accuser son adversaire de démagogie est lui-même parfois démagogique.", contexte: "Paradoxe politique" }], quiz: { correct: "Art de flatter les passions populaires pour conquérir le pouvoir.", wrongs: ["Science de la gestion de l'État.", "Philosophie du bien commun.", "Art de la négociation diplomatique."], anecdote: "À Athènes, les démagogues étaient d'abord des « guides du peuple » — le mot s'est dégradé avec l'histoire !" } },
  { mot: "Plébiscite", nature: "nom masculin", theme: "Politique", type: "mot", definition: "Vote par lequel le peuple approuve massivement une décision ou une personne.", etymologie: "Du latin plebiscitum — « décision de la plèbe »", exemples: [{ texte: "Sa victoire fut un véritable plébiscite avec 90% des suffrages.", contexte: "Élections" }, { texte: "Napoléon utilisa le plébiscite pour légitimer son pouvoir.", contexte: "Histoire" }, { texte: "Ce film est un plébiscite populaire — 5 millions d'entrées en une semaine.", contexte: "Usage figuré" }], quiz: { correct: "Vote d'approbation massive d'une décision ou personne.", wrongs: ["Rejet total d'une proposition.", "Débat contradictoire entre candidats.", "Décision prise par une assemblée restreinte."], anecdote: "Les Romains distinguaient la loi (votée par les patriciens) du plébiscite (décision de la plèbe) !" } },
  { mot: "Prévarication", nature: "nom féminin", theme: "Politique", type: "mot", definition: "Manquement grave d'un agent public à ses devoirs par corruption ou abus de pouvoir.", etymologie: "Du latin praevaricatio — « action de marcher de travers »", exemples: [{ texte: "La prévarication du fonctionnaire lui valut une condamnation.", contexte: "Droit" }, { texte: "L'histoire politique est jalonnée de prévarications.", contexte: "Histoire" }, { texte: "La lutte contre la prévarication est un pilier de la démocratie.", contexte: "Politique" }], quiz: { correct: "Manquement d'un agent public à ses devoirs par corruption.", wrongs: ["Excès de zèle dans une fonction.", "Erreur involontaire de gestion.", "Démission volontaire d'un poste."], anecdote: "Marcher de travers en latin — les Romains comprenaient que certains fonctionnaires ne marchaient pas droit !" } },
  // SPORT
  { mot: "Palmarès", nature: "nom masculin", theme: "Sport", type: "mot", definition: "Liste des victoires et distinctions obtenues par un sportif, une équipe ou une institution.", etymologie: "Du latin palma — « palme », symbole de victoire", exemples: [{ texte: "Son palmarès impressionnant incluait cinq Tours de France.", contexte: "Cyclisme" }, { texte: "Ce club a le palmarès le plus riche de l'histoire du football français.", contexte: "Football" }, { texte: "Son palmarès académique lui ouvrit les portes des meilleures universités.", contexte: "Usage figuré" }], quiz: { correct: "Liste des victoires et distinctions obtenues.", wrongs: ["Classement des défaites d'une équipe.", "Programme d'entraînement annuel.", "Contrat liant un sportif à son club."], anecdote: "La palme olympique grecque est l'ancêtre de tous nos palmarès — les vainqueurs recevaient une branche de palmier !" } },
  { mot: "Endurance", nature: "nom féminin", theme: "Sport", type: "mot", definition: "Capacité à résister longtemps à la fatigue physique ou morale ; ténacité dans l'effort.", etymologie: "Du latin indurare — « durcir »", exemples: [{ texte: "Le marathon est avant tout une épreuve d'endurance mentale.", contexte: "Athlétisme" }, { texte: "Son endurance face aux critiques força le respect de ses adversaires.", contexte: "Usage figuré" }, { texte: "Les courses de 24 heures testent l'endurance à son maximum.", contexte: "Sport automobile" }], quiz: { correct: "Capacité à résister longtemps à la fatigue physique ou morale.", wrongs: ["Vitesse maximale sur courte distance.", "Flexibilité musculaire exceptionnelle.", "Puissance explosive sur un effort bref."], anecdote: "Phidippide courut 42 km de Marathon à Athènes pour annoncer la victoire — et mourut en arrivant. Le premier marathonien !" } },
  { mot: "Quintuple", nature: "adjectif", theme: "Sport", type: "mot", definition: "Qui vaut cinq fois la mise ; qui a accompli quelque chose cinq fois.", etymologie: "Du latin quintus (cinquième) et plus (davantage)", exemples: [{ texte: "Ce basketteur quintuple champion NBA est considéré comme le GOAT.", contexte: "Basketball" }, { texte: "Le quintuple saut est une discipline athlétique exigeante.", contexte: "Athlétisme" }, { texte: "Cette équipe vise le quintuple — championnat, coupe, et trois autres titres.", contexte: "Football" }], quiz: { correct: "Qui a accompli ou vaut cinq fois quelque chose.", wrongs: ["Qui a gagné trois fois.", "Qui a perdu cinq fois de suite.", "Qui concourt dans cinq disciplines."], anecdote: "En 1999, Manchester United réalisa un triplé historique — le quintuple reste le Saint Graal du football !" } },
  // EXPRESSIONS
  { mot: "D'une pierre deux coups", nature: "expression", theme: "Vie quotidienne", type: "expression", definition: "Obtenir deux résultats avantageux avec une seule action.", etymologie: "Allusion à la chasse où un seul jet de pierre pouvait tuer deux oiseaux", exemples: [{ texte: "En faisant ses courses en vélo, il faisait d'une pierre deux coups : économies et sport.", contexte: "Usage courant" }, { texte: "Cette réforme fait d'une pierre deux coups : elle réduit les coûts et améliore le service.", contexte: "Politique" }, { texte: "Inviter ses collègues pour un dîner d'affaires, c'est faire d'une pierre deux coups.", contexte: "Professionnel" }], quiz: { correct: "Obtenir deux résultats avec une seule action.", wrongs: ["Échouer deux fois de suite.", "Hésiter entre deux options.", "Faire deux fois le même effort."], anecdote: "À l'origine c'était littéral — les chasseurs espéraient tuer deux oiseaux avec une seule pierre lancée !" } },
  { mot: "Avoir le cafard", nature: "expression", theme: "Vie quotidienne", type: "expression", definition: "Éprouver un sentiment de tristesse, de mélancolie, d'ennui profond.", etymologie: "Au XIXe siècle, les soldats français en Afrique du Nord souffraient de déprime — associée à l'insecte nocturne", exemples: [{ texte: "Il avait le cafard depuis que son ami était parti à l'étranger.", contexte: "Mélancolie" }, { texte: "La pluie du dimanche soir lui donnait toujours le cafard.", contexte: "État d'âme" }, { texte: "Appelle-moi si tu as le cafard — on ira prendre un verre.", contexte: "Amitié" }], quiz: { correct: "Éprouver un sentiment de tristesse et de mélancolie.", wrongs: ["Être très en colère.", "Avoir très faim.", "Se sentir exceptionnellement joyeux."], anecdote: "Les légionnaires français au Maghreb souffraient du spleen — l'insecte nocturne et sombre est devenu le symbole de leur mélancolie !" } },
  { mot: "Chercher midi à quatorze heures", nature: "expression", theme: "Vie quotidienne", type: "expression", definition: "Compliquer inutilement quelque chose de simple ; chercher des difficultés qui n'existent pas.", etymologie: "Impossible de trouver midi à 14h — l'heure n'existe pas, donc chercher l'impossible", exemples: [{ texte: "La solution était évidente, mais il cherchait midi à quatorze heures.", contexte: "Usage courant" }, { texte: "Ne cherche pas midi à quatorze heures — dis simplement la vérité.", contexte: "Conseil" }, { texte: "Les juristes aiment chercher midi à quatorze heures dans les contrats.", contexte: "Humour professionnel" }], quiz: { correct: "Compliquer inutilement quelque chose de simple.", wrongs: ["Arriver exactement à l'heure.", "Chercher une solution originale.", "Travailler jusqu'à très tard."], anecdote: "Midi ne peut pas être à 14h — l'expression dit qu'on cherche l'impossible dans ce qui est simple !" } },
  { mot: "Pédaler dans la choucroute", nature: "expression", theme: "Vie quotidienne", type: "expression", definition: "Ne pas avancer, s'agiter sans résultat, patauger dans une situation confuse.", etymologie: "Image comique du cycliste qui pédale dans un plat de choucroute — sans grip, sans avancement", exemples: [{ texte: "Sans direction claire, toute l'équipe pédalait dans la choucroute.", contexte: "Management" }, { texte: "Depuis trois semaines, ce projet pédale dans la choucroute.", contexte: "Travail" }, { texte: "J'ai l'impression de pédaler dans la choucroute avec ces démarches administratives.", contexte: "Frustration" }], quiz: { correct: "S'agiter sans avancer, patauger dans la confusion.", wrongs: ["Avancer très vite.", "Cuisiner de la choucroute.", "Faire du vélo en Alsace."], anecdote: "L'image est alsacienne — la choucroute est molle et épaisse, impossible d'y trouver prise. Parfait pour décrire l'impuissance !" } },
  { mot: "Les carottes sont cuites", nature: "expression", theme: "Vie quotidienne", type: "expression", definition: "Tout est perdu, la situation est irrémédiablement compromise.", etymologie: "Une carotte cuite ne peut pas redevenir crue — l'irréversibilité totale", exemples: [{ texte: "Avec ce retard, les carottes sont cuites pour la livraison.", contexte: "Urgence" }, { texte: "Il a avoué — les carottes sont cuites pour lui.", contexte: "Situation désespérée" }, { texte: "Sans financement supplémentaire, les carottes sont cuites pour le projet.", contexte: "Professionnel" }], quiz: { correct: "Tout est perdu, la situation est irrémédiablement compromise.", wrongs: ["Le dîner est prêt.", "Les efforts ont payé.", "La situation s'améliore."], anecdote: "La carotte cuite est irréversible — impossible de la rendre crue. Comme certaines situations !" } },
  { mot: "Avoir le beurre et l'argent du beurre", nature: "expression", theme: "Vie quotidienne", type: "expression", definition: "Vouloir bénéficier de deux avantages contradictoires sans concession.", etymologie: "Image du marché : vendre son beurre et garder l'argent tout en le conservant — impossible", exemples: [{ texte: "Il voulait être libre et stable — avoir le beurre et l'argent du beurre.", contexte: "Contradiction" }, { texte: "Cette négociation voulait le beurre et l'argent du beurre — ça a échoué.", contexte: "Négociation" }, { texte: "On ne peut pas avoir le beurre et l'argent du beurre en politique.", contexte: "Réalisme" }], quiz: { correct: "Vouloir bénéficier de deux avantages contradictoires.", wrongs: ["Faire ses courses au marché.", "Économiser pour acheter du beurre.", "Refuser tout compromis."], anecdote: "La version complète est encore plus drôle : « avoir le beurre, l'argent du beurre et le sourire de la crémière » !" } },
]

export default async function handler(req: NextApiRequest, res: NextApiResponse) {
  if (req.method !== 'GET') return res.status(405).json({ error: 'Méthode non autorisée' })

  const today = new Date().toISOString().split('T')[0]
  const debut = new Date('2024-01-01').getTime()
  const joursEcoules = Math.floor((new Date().getTime() - debut) / (1000 * 60 * 60 * 24))

  // Sélectionner 3 entrées de catégories différentes
  const categories = [...TOUTES_CATEGORIES]
  const catsShuffle = categories.sort(() => (Math.sin(joursEcoules) * 10000) % 1 - 0.5)
  const troisCats = catsShuffle.slice(0, 3)

  const mots = troisCats.map((cat, i) => {
    const motsCategorie = BANQUE.filter(m => m.theme === cat)
    if (motsCategorie.length === 0) return BANQUE[i % BANQUE.length]
    const idx = (joursEcoules + i * 7) % motsCategorie.length
    return { ...motsCategorie[idx], date: today }
  })

  // Insérer une expression occasionnellement (tous les 3 jours)
  if (joursEcoules % 3 === 0) {
    const expressions = BANQUE.filter(m => m.type === 'expression')
    const expr = expressions[joursEcoules % expressions.length]
    mots[2] = { ...expr, date: today }
  }

  return res.status(200).json(mots)
}
